#############################################
#  Custom Hyprland Config (gyro’s setup)
#############################################

# -------- MONITORS --------
monitor=HDMI-A-1,2560x1440@100,0x0,1
monitor=eDP-1,disable

# misc {
#    monitor_reload_on_connect = true
# }

# -------- DECORATION --------
#decoration {
#    rounding = 8
#    blur = yes
#    blur_size = 8
#    blur_passes = 3
#    drop_shadow = yes
#}

# -------- GENERAL --------
general {
    gaps_in = 6
    gaps_out = 12
    border_size = 2
    col.active_border = rgb(89b4fa)
    col.inactive_border = rgb(313244)
    layout = master
}

# -------- KEYBINDS --------
bind = SUPER, Return, exec, kitty
bind = SUPER, F, exec, firefox
bind = SUPER, W, exec, wofi --show drun
bind = SUPER, Q, killactive, 
bind = SUPER, M, exit, 
bind = SUPER, SPACE, togglefloating,
bind = SUPER, S, exec, hyprctl dispatch togglefloating
bind = SUPER SHIFT, W, exec, ~/.config/waybar/scripts/launch.sh # reload waybar

# Move between windows
bind = SUPER, H, movefocus, l
bind = SUPER, L, movefocus, r
bind = SUPER, K, movefocus, u
bind = SUPER, J, movefocus, d

# Resize floating window
binde = SUPER ALT, H, resizeactive, -50 0
binde = SUPER ALT, L, resizeactive, 50 0
binde = SUPER ALT, K, resizeactive, 0 -50
binde = SUPER ALT, J, resizeactive, 0 50

# -------- AUTOSTART APPS --------
exec-once = waybar &
exec-once = swaybg -i ~/Pictures/wallpapers/forest.jpg -m fill
exec-once = wlsunset -l 26.2 -L 78.2
exec-once = nm-applet &
exec-once = blueman-applet &
# exec-once = swww-daemon
exec-once = hyprpaper &
exec-once = ~/.config/hypr/scripts/wallpaper-rotate.sh &

# -------- ENV --------
env = XCURSOR_SIZE,24
env = GTK_THEME,Catppuccin-Mocha
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = GDK_BACKEND,wayland,x11
env = QT_QPA_PLATFORM,wayland;xcb

