font_family      FantasqueSansM Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 16.0

hell_integration no-cursor
cursor_shape block
cursor_blink_interval 0
window_padding_width 0

background #0c1115
foreground #ffffff
cursor #6c6c6c
selection_background #bd2523
selection_foreground #0c1115
